# Generated by Django 6.0.5 on 2026-05-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0003_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='showroom_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='brand',
            name='showroom_location',
            field=models.TextField(blank=True, default='', help_text="Full address of the showroom where this brand's cars are available"),
        ),
        migrations.AddField(
            model_name='brand',
            name='showroom_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
